model_name: PatchTST
model_architecture:
  layers:
  - name: decomp_module
    type: series_decomp
    parameters: 0
  - name: model_trend
    type: PatchTST_backbone
    parameters: 11807
  - name: model_res
    type: PatchTST_backbone
    parameters: 11807
  - name: classifier
    type: Sequential
    parameters: 2095
  total_parameters: 25709
  trainable_parameters: 25707
training_config:
  batch_size: 128
  learning_rate: 5.0e-05
  epochs: 100
  seed: 10
  weight_decay: 1.0e-05
  beta: 0.99
  gamma: 2.5
  gpu: true
  optimizer: AdamW
  loss_function: CB_loss with focal
  scheduler: LambdaLR with warmup and cosine decay
performance_metrics:
  best_accuracy: 0
  best_epoch: 0
  final_metrics:
    accuracy: 0
    f1_score: 0
    precision: 0
    recall: 0
    kappa: 0
