_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.9.20
        t:
            "1":
                - 1
                - 5
                - 53
                - 55
            "2":
                - 1
                - 5
                - 53
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.9.20
            "5": 0.19.8
            "8":
                - 3
                - 5
            "12": 0.19.8
            "13": windows-amd64
batch_size:
    value: 1024
beta:
    value: 0.9999
epochs:
    value: 100
gamma:
    value: 5
learning_rate:
    value: 0.0001
loss_ratio:
    value: 0.9
model_d_model:
    value: 128
model_patch_len:
    value: 8
model_stride:
    value: 4
